[project]
name = "project"
version = "0.0.0"
description = "Add your description here"
authors = [
    {name = "Kevin Schaul", email = "kevin.schaul@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.pyright]
venvPath = "."
venv = ".venv"
extraPaths = ["."]
